In [1]:
import numpy as np
import networkx as nx
from scipy.linalg import *

In [2]:
#flows
X = np.array([[0, 5, 0, 0], [-5, 0, 3, -1], [0, -3, 0, 1], [0, 1, -1, 0]])
#adjacency
A = X.copy()
A[A != 0] = 1

#divergence of flow matrix
D = np.sum(X, 1).dot(np.eye(4,4))

#Laplacian
L = np.sum(A,1).dot(np.eye(4,4)) + -1*A

In [3]:
#svd to find domain/codomain of Laplacian
U, S, V = np.linalg.svd(L)

In [4]:
print(U, S, V)

[[ -5.55331770e-01   4.27245070e-01  -2.62681588e-16   7.13490207e-01]
 [ -4.78855079e-01  -8.65719992e-01   1.38051881e-17   1.45693885e-01]
 [ -4.80782923e-01   1.84378069e-01  -7.07106781e-01  -4.84615836e-01]
 [ -4.80782923e-01   1.84378069e-01   7.07106781e-01  -4.84615836e-01]] [ 6.37726751  1.49374707  1.          0.31492675] [[ -2.37860120e-01  -7.00983684e-01  -4.75417941e-01  -4.75417941e-01]
 [  5.32888884e-01  -6.72910147e-01   3.62781870e-01   3.62781870e-01]
 [  0.00000000e+00  -6.43383336e-17  -7.07106781e-01   7.07106781e-01]
 [ -8.12066500e-01  -2.36249462e-01   3.77315645e-01   3.77315645e-01]]


In [5]:
#HodgeRank
L = np.sum(A,1).dot(np.eye(4,4)) + -1 * A
Lstar = np.linalg.pinv(L)
#"Rank"
sstar = -1*Lstar.dot(D)

In [6]:
sstar

array([ 9.,  5., -5., -7.])